export const refs = {
  gallery: document.querySelector('#gallery'),
  galleryCard: document.querySelector('.gallery__card'),
  closeButton: document.querySelector('.modal__close-button'),
  closeSvg: document.querySelector('.modal__icon-close'),
  closePath1: document.querySelector('#modal__close-path1'),
  closePath2: document.querySelector('#modal__close-path2'),
  buttonCountry: document.querySelector('#countryBtn'),
  selectList: document.querySelector('.select'),
  formSearchEvents: document.querySelector('#search-form'),
  buttonSearchCountry: document.querySelector('.choose-button'),
  backdrop: document.querySelector('.backdrop'),
  modal: document.querySelector('.modal'),
  paginationAnchorRef: document.querySelector('#tui-pagination-container'),
  select: document.querySelector('#select-country'),
  moreAuthorBtn: document.querySelector('.modal__more-button'),
  paginationDiv: document.querySelector('.pagination-box'),
  logo: document.querySelector('#logo'),
};
